[package]
name = "stc-scriptions"
version = "1.0.1"

[addresses]
StarcoinFramework = "0x1"
STCScriptionAdmin = "0x1ba719ac8a26bb941e8016831b3550cd"

[dependencies]
StarcoinFramework = { git = "https://github.com/starcoinorg/starcoin-framework.git", rev = "345a3900a0064dc57a9560235bc72c12f03448b1" }